### ISSUE TITLE
Supporting for ES 7.0.1 / 7.1

### ISSUE THREAD

**Issue by EvgenijZaluzhanskij** [papahigh/elasticsearch-russian-phonetics#2]
If its possible - add supporting of ES 7.0.1 / 7.1

**Comment by npapakha** [comment]
@EvgenijZaluzhanskij Ok, i'll add binaries.

**Comment by npapakha** [comment]
@EvgenijZaluzhanskij Done https://github.com/papahigh/elasticsearch-russian-phonetics/blob/master/releases.asciidoc
