### ISSUE TITLE
Support for ES 7.6.2

### ISSUE THREAD

**Issue by vasishakd** [papahigh/elasticsearch-russian-phonetics#3]

**Comment by npapakha** [comment]
Hi @vasishakd! I'll update plugin binaries

**Comment by npapakha** [comment]
@vasishakd check this link https://github.com/papahigh/elasticsearch-russian-phonetics/raw/7.6.2/esplugin/plugin-distributions/analysis-russian-phonetic-7.6.2.zip

Try running the following:

`bin/elasticsearch-plugin install https://github.com/papahigh/elasticsearch-russian-phonetics/raw/7.6.2/esplugin/plugin-distributions/analysis-russian-phonetic-7.6.2.zip`
